#! /bin/sh
#
#pgrep -x sxhkd > /dev/null || sxhkd &
#
#bspc monitor -d I II III IV V VI VII VIII IX X
#
#bspc config border_width         2
#bspc config window_gap          12
#
#bspc config split_ratio          0.52
#bspc config borderless_monocle   true
#bspc config gapless_monocle      true
#
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off
#~/.config/polybar/./launch.sh --hack

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width        3
bspc config window_gap          2
bspc config top_padding 0
#bspc config buttom_padding 0
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

xrandr --output HDMI-0 --primary --mode 1920x1080 --rate 59.94 --scale 0.8x0.8 --output DVI-1  --mode 1920x1080 --rate 59.95 --left-of HDMI-0
bspc config focus_follows_pointer true

# variety
# Terminate already running bar instances
#variety

#  Picom
# Terminate already running bar instances
#~/.config/start/picom.sh

picom --experimental-backends &

# polybar
# Terminate already running bar instances
~/.config/polybar/launch.sh --hack

bspc config top_padding 0
bspc config buttom_padding 0
